services:
  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=1
      # Tell Kafka which listener name is used by the controller role:
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Map listener names to protocols:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      # Single-node controller quorum (id@host:port):
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      # Define listeners: one for client traffic, one for controller traffic:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      # How clients outside the container reach the broker:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      # Inter-broker traffic will use the PLAINTEXT listener:
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Create topics automatically if a producer/consumer references them:
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    # Optional but recommended so data survives container restart:
    # volumes:
    #   - kafka_data:/bitnami/kafka

# volumes:
#   kafka_data:

